Config:
  # Change the language of VCT within the game. The list of available languages is located at: core/messages
  language: en_US
  # The plugin will attempt to auto-update when it finds a new version.
  auto_update: false
  # The plugin will send an update notification when it finds a new version if auto-update is disabled.
  update_notification: true
  # When the timer ends, how many ticks should wait to hide the boss bar (1 second = 20 ticks)
  ticks_hide_after_ending: 60
  # Which text formatter to use (MINIMESSAGE, LEGACY or UNIVERSAL)
  # Please note that UNIVERSAL requires the most resources, but supports all types of formats.

  # (&x&f&f&5&5&f&fc and &#ff55ff LEGACY - <color:#ff55ff> MINIMESSAGE)
  text_format: LEGACY
  # How many ticks should the boss bar text refresh?
  # It is usually used when you use animations to make them more fluid.
  refresh_ticks: 10
  # Should the plugin save and load the timer states when the server is closed and opened?
  save_state_timers: true
  # Enables additional debug logs in console to help diagnose issues.
  debug_mode: false

Timers:
  default:
    text: "%HH%:%MM%:%SS%" # The text of the boss bar (%HH% hours, %MM% minutes, %SS% seconds)
    sound: UI_BUTTON_CLICK # The sound of the timer every second
    sound_volume: 1.0 # The volume of the sound (1.0 is 100%)
    sound_pitch: 1.0 # The pitch of the sound (1.0 is normal pitch)
    bossbar_color: WHITE # The boss bar color is BLUE, GREEN, PINK, PURPLE, RED, WHITE, or YELLOW.
    bossbar_style: SOLID # The boss bar style is SOLID, SEGMENTED_6, SEGMENTED_10, SEGMENTED_12, or SEGMENTED_20.
    enabled: true # Defines whether this timer is available for selection.
    sound_enabled: false # Defines whether this timer plays sound every second.

  timer_1:
    text: "&aI'm the Timer 1 :D (%HH%:%MM%:%SS%)"
    sound: UI_BUTTON_CLICK
    sound_volume: 0.5
    sound_pitch: 2.0
    bossbar_color: GREEN
    bossbar_style: SEGMENTED_6
    enabled: true
    sound_enabled: true